<?xml version="1.0" encoding="utf-8"?>
<Database Name="ClarianHealthIN_Archive" Class="ArchiveClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=stageimp100;Initial Catalog=ClarianHealthIN_Archive;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ClarianHealthIN_ArchiveConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DtsRdeStdArchive" Member="DtsRdeStdArchives">
    <Type Name="DtsRdeStdArchive">
      <Column Name="headerRow_tk" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="siteCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sendingApplication" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="messageControlId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="messageDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="patient" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="patientAccountNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="patientName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="roombed" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="facilityId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="checkSumId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datasource" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="datasourceType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="logTk" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UniversalMRN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BirthDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DtsRdeStdArchive_DtsRdeOrdersStdArchive" Member="DtsRdeOrdersStdArchives" ThisKey="headerRow_tk" OtherKey="headerRow_tk" Type="DtsRdeOrdersStdArchive" />
    </Type>
  </Table>
  <Table Name="dbo.DtsRdeOrdersStdArchive" Member="DtsRdeOrdersStdArchives">
    <Type Name="DtsRdeOrdersStdArchive">
      <Column Name="headerRow_tk" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="orderRow_tk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="orderControl" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="orderEffectiveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="transactionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="prescriptionNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="placerOrderNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fillerOrderNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="parentPlacerOrderNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="parentFillerOrderNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="quantityTiming_Quantity" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="quantityTiming_QuantityUnits" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="quantityTiming_IntervalRepeatPattern" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="quantityTiming_IntervalExplicitTimeInterval" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="quantityTiming_Duration" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="quantityTiming_StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="quantityTiming_EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="quantityTiming_Priority" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="quantityTiming_Condition" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="quantityTiming_Text" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="orderingProviderId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="orderingProviderName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_RequestedGiveCode_Identifier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_RequestedGiveCode_Text" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_RequestedGiveCode_NameOfCodingSystem" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_RequestedGiveCode_AlternateText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_MinimumRequestedGiveAmount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_MaximumRequestedGiveAmount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_NumberRefills" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_RequestedGivePerTimeUnit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_RequestedGiveRateAmount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_RequestedGiveRateUnits" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_RXR_Route" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_RXR_Site" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_RXR_AdministrationDevice" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prescription_RXR_AdministrationMethod" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_GiveUnits" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_GiveDosageForm" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_MinimumGiveAmount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_MaximumGiveAmount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_DispenseAmount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_DispenseUnits" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_NumberOfRefills" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_NumberOfRefillsRemaining" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_NumberOfRefillsDoseDispensed" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_GivePerTimeUnit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_GiveRateAmount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_GiveRateUnits" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_QuantityTiming_Quantity" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_QuantityTiming_QuantityUnits" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_QuantityTiming_IntervalRepeatPattern" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_QuantityTiming_IntervalExplicitTimeInterval" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="rxe_QuantityTiming_Duration" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_QuantityTiming_StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="rxe_QuantityTiming_EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="rxe_QuantityTiming_Priority" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_QuantityTiming_Condition" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_QuantityTiming_Text" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_GiveCode_Identifier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_GiveCode_Text" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_GiveCode_NameOfCodingSystem" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_GiveCode_AlternateText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_Pharmisist_Identifier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxe_Pharmisist_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxr_Route" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxr_Site" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxr_AdministrationDevice" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="rxr_AdministrationMethod" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="DtsRdeOrdersStdArchive_DtsRdeOrdersRxcStdArchive" Member="DtsRdeOrdersRxcStdArchives" ThisKey="headerRow_tk,orderRow_tk" OtherKey="headerRow_tk,orderRow_tk" Type="DtsRdeOrdersRxcStdArchive" />
      <Association Name="DtsRdeStdArchive_DtsRdeOrdersStdArchive" Member="DtsRdeStdArchive" ThisKey="headerRow_tk" OtherKey="headerRow_tk" Type="DtsRdeStdArchive" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DtsRdeOrdersRxcStdArchive" Member="DtsRdeOrdersRxcStdArchives">
    <Type Name="DtsRdeOrdersRxcStdArchive">
      <Column Name="headerRow_tk" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="orderRow_tk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="orderRxcRow_tk" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RDE_Orders_RXC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_RxComponentType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentCodeIdentifier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentCodeText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentCodeAlternateText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentCodeNameOfCodingSystem" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentAmount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentUnitsIdentifier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentUnitsText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentUnitsAlternateText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentUnitsNameOfCodingSystem" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentStrength" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentStrengthUnitsIdentifier" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentStrengthUnitsText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentStrengthUnitsAlternateText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_ComponentStrengthUnitsNameOfCodingSystem" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RDE_Orders_RXC_SupplementaryCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="DtsRdeOrdersStdArchive_DtsRdeOrdersRxcStdArchive" Member="DtsRdeOrdersStdArchive" ThisKey="headerRow_tk,orderRow_tk" OtherKey="headerRow_tk,orderRow_tk" Type="DtsRdeOrdersStdArchive" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>