#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="")]
	public partial class ArchiveClassesDataContext : System.Data.Linq.DataContext
	{
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
        

    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void OnCreated()
    {
        base.CommandTimeout = 600;
        base.ObjectTrackingEnabled = false;
    }
    partial void InsertDtsRdeStdArchive(DtsRdeStdArchive instance);
    partial void UpdateDtsRdeStdArchive(DtsRdeStdArchive instance);
    partial void DeleteDtsRdeStdArchive(DtsRdeStdArchive instance);
    partial void InsertDtsRdeOrdersStdArchive(DtsRdeOrdersStdArchive instance);
    partial void UpdateDtsRdeOrdersStdArchive(DtsRdeOrdersStdArchive instance);
    partial void DeleteDtsRdeOrdersStdArchive(DtsRdeOrdersStdArchive instance);
    partial void InsertDtsRdeOrdersRxcStdArchive(DtsRdeOrdersRxcStdArchive instance);
    partial void UpdateDtsRdeOrdersRxcStdArchive(DtsRdeOrdersRxcStdArchive instance);
    partial void DeleteDtsRdeOrdersRxcStdArchive(DtsRdeOrdersRxcStdArchive instance);
    #endregion



    
        
        public ArchiveClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings[""].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ArchiveClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArchiveClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArchiveClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArchiveClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DtsRdeStdArchive> DtsRdeStdArchives
		{
			get
			{
				return this.GetTable<DtsRdeStdArchive>();
			}
		}
		
		public System.Data.Linq.Table<DtsRdeOrdersStdArchive> DtsRdeOrdersStdArchives
		{
			get
			{
				return this.GetTable<DtsRdeOrdersStdArchive>();
			}
		}
		
		public System.Data.Linq.Table<DtsRdeOrdersRxcStdArchive> DtsRdeOrdersRxcStdArchives
		{
			get
			{
				return this.GetTable<DtsRdeOrdersRxcStdArchive>();
			}
		}
	}
	
	[Table(Name="dbo.DtsRdeStdArchive")]
	public partial class DtsRdeStdArchive : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _headerRow_tk;
		
		private string _siteCode;
		
		private string _sendingApplication;
		
		private string _messageControlId;
		
		private System.Nullable<System.DateTime> _messageDateTime;
		
		private string _patient;
		
		private string _patientAccountNumber;
		
		private string _patientName;
		
		private string _location;
		
		private string _roombed;
		
		private string _facilityId;
		
		private System.Nullable<int> _checkSumId;
		
		private string _datasource;
		
		private int _datasourceType;
		
		private System.Nullable<decimal> _logTk;
		
		private string _Gender;
		
		private string _UniversalMRN;
		
		private System.Nullable<System.DateTime> _BirthDateTime;
		
		private System.Nullable<System.DateTime> _CreatedDateTime;
		
		private EntitySet<DtsRdeOrdersStdArchive> _DtsRdeOrdersStdArchives;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnheaderRow_tkChanging(decimal value);
    partial void OnheaderRow_tkChanged();
    partial void OnsiteCodeChanging(string value);
    partial void OnsiteCodeChanged();
    partial void OnsendingApplicationChanging(string value);
    partial void OnsendingApplicationChanged();
    partial void OnmessageControlIdChanging(string value);
    partial void OnmessageControlIdChanged();
    partial void OnmessageDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnmessageDateTimeChanged();
    partial void OnpatientChanging(string value);
    partial void OnpatientChanged();
    partial void OnpatientAccountNumberChanging(string value);
    partial void OnpatientAccountNumberChanged();
    partial void OnpatientNameChanging(string value);
    partial void OnpatientNameChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OnroombedChanging(string value);
    partial void OnroombedChanged();
    partial void OnfacilityIdChanging(string value);
    partial void OnfacilityIdChanged();
    partial void OncheckSumIdChanging(System.Nullable<int> value);
    partial void OncheckSumIdChanged();
    partial void OndatasourceChanging(string value);
    partial void OndatasourceChanged();
    partial void OndatasourceTypeChanging(int value);
    partial void OndatasourceTypeChanged();
    partial void OnlogTkChanging(System.Nullable<decimal> value);
    partial void OnlogTkChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnUniversalMRNChanging(string value);
    partial void OnUniversalMRNChanged();
    partial void OnBirthDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthDateTimeChanged();
    partial void OnCreatedDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateTimeChanged();
    #endregion
		
		public DtsRdeStdArchive()
		{
			this._DtsRdeOrdersStdArchives = new EntitySet<DtsRdeOrdersStdArchive>(new Action<DtsRdeOrdersStdArchive>(this.attach_DtsRdeOrdersStdArchives), new Action<DtsRdeOrdersStdArchive>(this.detach_DtsRdeOrdersStdArchives));
			OnCreated();
		}
		
		[Column(Storage="_headerRow_tk", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal headerRow_tk
		{
			get
			{
				return this._headerRow_tk;
			}
			set
			{
				if ((this._headerRow_tk != value))
				{
					this.OnheaderRow_tkChanging(value);
					this.SendPropertyChanging();
					this._headerRow_tk = value;
					this.SendPropertyChanged("headerRow_tk");
					this.OnheaderRow_tkChanged();
				}
			}
		}
		
		[Column(Storage="_siteCode", DbType="VarChar(50)")]
		public string siteCode
		{
			get
			{
				return this._siteCode;
			}
			set
			{
				if ((this._siteCode != value))
				{
					this.OnsiteCodeChanging(value);
					this.SendPropertyChanging();
					this._siteCode = value;
					this.SendPropertyChanged("siteCode");
					this.OnsiteCodeChanged();
				}
			}
		}
		
		[Column(Storage="_sendingApplication", DbType="VarChar(50)")]
		public string sendingApplication
		{
			get
			{
				return this._sendingApplication;
			}
			set
			{
				if ((this._sendingApplication != value))
				{
					this.OnsendingApplicationChanging(value);
					this.SendPropertyChanging();
					this._sendingApplication = value;
					this.SendPropertyChanged("sendingApplication");
					this.OnsendingApplicationChanged();
				}
			}
		}
		
		[Column(Storage="_messageControlId", DbType="VarChar(50)")]
		public string messageControlId
		{
			get
			{
				return this._messageControlId;
			}
			set
			{
				if ((this._messageControlId != value))
				{
					this.OnmessageControlIdChanging(value);
					this.SendPropertyChanging();
					this._messageControlId = value;
					this.SendPropertyChanged("messageControlId");
					this.OnmessageControlIdChanged();
				}
			}
		}
		
		[Column(Storage="_messageDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> messageDateTime
		{
			get
			{
				return this._messageDateTime;
			}
			set
			{
				if ((this._messageDateTime != value))
				{
					this.OnmessageDateTimeChanging(value);
					this.SendPropertyChanging();
					this._messageDateTime = value;
					this.SendPropertyChanged("messageDateTime");
					this.OnmessageDateTimeChanged();
				}
			}
		}
		
		[Column(Storage="_patient", DbType="VarChar(50)")]
		public string patient
		{
			get
			{
				return this._patient;
			}
			set
			{
				if ((this._patient != value))
				{
					this.OnpatientChanging(value);
					this.SendPropertyChanging();
					this._patient = value;
					this.SendPropertyChanged("patient");
					this.OnpatientChanged();
				}
			}
		}
		
		[Column(Storage="_patientAccountNumber", DbType="VarChar(50)")]
		public string patientAccountNumber
		{
			get
			{
				return this._patientAccountNumber;
			}
			set
			{
				if ((this._patientAccountNumber != value))
				{
					this.OnpatientAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._patientAccountNumber = value;
					this.SendPropertyChanged("patientAccountNumber");
					this.OnpatientAccountNumberChanged();
				}
			}
		}
		
		[Column(Storage="_patientName", DbType="VarChar(50)")]
		public string patientName
		{
			get
			{
				return this._patientName;
			}
			set
			{
				if ((this._patientName != value))
				{
					this.OnpatientNameChanging(value);
					this.SendPropertyChanging();
					this._patientName = value;
					this.SendPropertyChanged("patientName");
					this.OnpatientNameChanged();
				}
			}
		}
		
		[Column(Storage="_location", DbType="VarChar(50)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[Column(Storage="_roombed", DbType="VarChar(50)")]
		public string roombed
		{
			get
			{
				return this._roombed;
			}
			set
			{
				if ((this._roombed != value))
				{
					this.OnroombedChanging(value);
					this.SendPropertyChanging();
					this._roombed = value;
					this.SendPropertyChanged("roombed");
					this.OnroombedChanged();
				}
			}
		}
		
		[Column(Storage="_facilityId", DbType="VarChar(50)")]
		public string facilityId
		{
			get
			{
				return this._facilityId;
			}
			set
			{
				if ((this._facilityId != value))
				{
					this.OnfacilityIdChanging(value);
					this.SendPropertyChanging();
					this._facilityId = value;
					this.SendPropertyChanged("facilityId");
					this.OnfacilityIdChanged();
				}
			}
		}
		
		[Column(Storage="_checkSumId", DbType="Int")]
		public System.Nullable<int> checkSumId
		{
			get
			{
				return this._checkSumId;
			}
			set
			{
				if ((this._checkSumId != value))
				{
					this.OncheckSumIdChanging(value);
					this.SendPropertyChanging();
					this._checkSumId = value;
					this.SendPropertyChanged("checkSumId");
					this.OncheckSumIdChanged();
				}
			}
		}
		
		[Column(Storage="_datasource", DbType="VarChar(200)")]
		public string datasource
		{
			get
			{
				return this._datasource;
			}
			set
			{
				if ((this._datasource != value))
				{
					this.OndatasourceChanging(value);
					this.SendPropertyChanging();
					this._datasource = value;
					this.SendPropertyChanged("datasource");
					this.OndatasourceChanged();
				}
			}
		}
		
		[Column(Storage="_datasourceType", DbType="Int NOT NULL")]
		public int datasourceType
		{
			get
			{
				return this._datasourceType;
			}
			set
			{
				if ((this._datasourceType != value))
				{
					this.OndatasourceTypeChanging(value);
					this.SendPropertyChanging();
					this._datasourceType = value;
					this.SendPropertyChanged("datasourceType");
					this.OndatasourceTypeChanged();
				}
			}
		}
		
		[Column(Storage="_logTk", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> logTk
		{
			get
			{
				return this._logTk;
			}
			set
			{
				if ((this._logTk != value))
				{
					this.OnlogTkChanging(value);
					this.SendPropertyChanging();
					this._logTk = value;
					this.SendPropertyChanged("logTk");
					this.OnlogTkChanged();
				}
			}
		}
		
		[Column(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[Column(Storage="_UniversalMRN", DbType="VarChar(50)")]
		public string UniversalMRN
		{
			get
			{
				return this._UniversalMRN;
			}
			set
			{
				if ((this._UniversalMRN != value))
				{
					this.OnUniversalMRNChanging(value);
					this.SendPropertyChanging();
					this._UniversalMRN = value;
					this.SendPropertyChanged("UniversalMRN");
					this.OnUniversalMRNChanged();
				}
			}
		}
		
		[Column(Storage="_BirthDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> BirthDateTime
		{
			get
			{
				return this._BirthDateTime;
			}
			set
			{
				if ((this._BirthDateTime != value))
				{
					this.OnBirthDateTimeChanging(value);
					this.SendPropertyChanging();
					this._BirthDateTime = value;
					this.SendPropertyChanged("BirthDateTime");
					this.OnBirthDateTimeChanged();
				}
			}
		}
		
		[Column(Storage="_CreatedDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDateTime
		{
			get
			{
				return this._CreatedDateTime;
			}
			set
			{
				if ((this._CreatedDateTime != value))
				{
					this.OnCreatedDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreatedDateTime = value;
					this.SendPropertyChanged("CreatedDateTime");
					this.OnCreatedDateTimeChanged();
				}
			}
		}
		
		[Association(Name="DtsRdeStdArchive_DtsRdeOrdersStdArchive", Storage="_DtsRdeOrdersStdArchives", ThisKey="headerRow_tk", OtherKey="headerRow_tk")]
		public EntitySet<DtsRdeOrdersStdArchive> DtsRdeOrdersStdArchives
		{
			get
			{
				return this._DtsRdeOrdersStdArchives;
			}
			set
			{
				this._DtsRdeOrdersStdArchives.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DtsRdeOrdersStdArchives(DtsRdeOrdersStdArchive entity)
		{
			this.SendPropertyChanging();
			entity.DtsRdeStdArchive = this;
		}
		
		private void detach_DtsRdeOrdersStdArchives(DtsRdeOrdersStdArchive entity)
		{
			this.SendPropertyChanging();
			entity.DtsRdeStdArchive = null;
		}
	}
	
	[Table(Name="dbo.DtsRdeOrdersStdArchive")]
	public partial class DtsRdeOrdersStdArchive : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _headerRow_tk;
		
		private int _orderRow_tk;
		
		private string _orderControl;
		
		private System.Nullable<System.DateTime> _orderEffectiveDate;
		
		private System.Nullable<System.DateTime> _transactionDate;
		
		private string _prescriptionNumber;
		
		private string _placerOrderNumber;
		
		private string _fillerOrderNumber;
		
		private string _parentPlacerOrderNumber;
		
		private string _parentFillerOrderNumber;
		
		private string _quantityTiming_Quantity;
		
		private string _quantityTiming_QuantityUnits;
		
		private string _quantityTiming_IntervalRepeatPattern;
		
		private string _quantityTiming_IntervalExplicitTimeInterval;
		
		private string _quantityTiming_Duration;
		
		private System.Nullable<System.DateTime> _quantityTiming_StartTime;
		
		private System.Nullable<System.DateTime> _quantityTiming_EndTime;
		
		private string _quantityTiming_Priority;
		
		private string _quantityTiming_Condition;
		
		private string _quantityTiming_Text;
		
		private string _orderingProviderId;
		
		private string _orderingProviderName;
		
		private string _prescription_RequestedGiveCode_Identifier;
		
		private string _prescription_RequestedGiveCode_Text;
		
		private string _prescription_RequestedGiveCode_NameOfCodingSystem;
		
		private string _prescription_RequestedGiveCode_AlternateText;
		
		private string _prescription_MinimumRequestedGiveAmount;
		
		private string _prescription_MaximumRequestedGiveAmount;
		
		private string _prescription_NumberRefills;
		
		private string _prescription_RequestedGivePerTimeUnit;
		
		private string _prescription_RequestedGiveRateAmount;
		
		private string _prescription_RequestedGiveRateUnits;
		
		private string _prescription_RXR_Route;
		
		private string _prescription_RXR_Site;
		
		private string _prescription_RXR_AdministrationDevice;
		
		private string _prescription_RXR_AdministrationMethod;
		
		private string _rxe_GiveUnits;
		
		private string _rxe_GiveDosageForm;
		
		private string _rxe_MinimumGiveAmount;
		
		private string _rxe_MaximumGiveAmount;
		
		private string _rxe_DispenseAmount;
		
		private string _rxe_DispenseUnits;
		
		private string _rxe_NumberOfRefills;
		
		private string _rxe_NumberOfRefillsRemaining;
		
		private string _rxe_NumberOfRefillsDoseDispensed;
		
		private string _rxe_GivePerTimeUnit;
		
		private string _rxe_GiveRateAmount;
		
		private string _rxe_GiveRateUnits;
		
		private string _rxe_QuantityTiming_Quantity;
		
		private string _rxe_QuantityTiming_QuantityUnits;
		
		private string _rxe_QuantityTiming_IntervalRepeatPattern;
		
		private string _rxe_QuantityTiming_IntervalExplicitTimeInterval;
		
		private string _rxe_QuantityTiming_Duration;
		
		private System.Nullable<System.DateTime> _rxe_QuantityTiming_StartTime;
		
		private System.Nullable<System.DateTime> _rxe_QuantityTiming_EndTime;
		
		private string _rxe_QuantityTiming_Priority;
		
		private string _rxe_QuantityTiming_Condition;
		
		private string _rxe_QuantityTiming_Text;
		
		private string _rxe_GiveCode_Identifier;
		
		private string _rxe_GiveCode_Text;
		
		private string _rxe_GiveCode_NameOfCodingSystem;
		
		private string _rxe_GiveCode_AlternateText;
		
		private string _rxe_Pharmisist_Identifier;
		
		private string _rxe_Pharmisist_Name;
		
		private string _rxr_Route;
		
		private string _rxr_Site;
		
		private string _rxr_AdministrationDevice;
		
		private string _rxr_AdministrationMethod;
		
		private EntitySet<DtsRdeOrdersRxcStdArchive> _DtsRdeOrdersRxcStdArchives;
		
		private EntityRef<DtsRdeStdArchive> _DtsRdeStdArchive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnheaderRow_tkChanging(decimal value);
    partial void OnheaderRow_tkChanged();
    partial void OnorderRow_tkChanging(int value);
    partial void OnorderRow_tkChanged();
    partial void OnorderControlChanging(string value);
    partial void OnorderControlChanged();
    partial void OnorderEffectiveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnorderEffectiveDateChanged();
    partial void OntransactionDateChanging(System.Nullable<System.DateTime> value);
    partial void OntransactionDateChanged();
    partial void OnprescriptionNumberChanging(string value);
    partial void OnprescriptionNumberChanged();
    partial void OnplacerOrderNumberChanging(string value);
    partial void OnplacerOrderNumberChanged();
    partial void OnfillerOrderNumberChanging(string value);
    partial void OnfillerOrderNumberChanged();
    partial void OnparentPlacerOrderNumberChanging(string value);
    partial void OnparentPlacerOrderNumberChanged();
    partial void OnparentFillerOrderNumberChanging(string value);
    partial void OnparentFillerOrderNumberChanged();
    partial void OnquantityTiming_QuantityChanging(string value);
    partial void OnquantityTiming_QuantityChanged();
    partial void OnquantityTiming_QuantityUnitsChanging(string value);
    partial void OnquantityTiming_QuantityUnitsChanged();
    partial void OnquantityTiming_IntervalRepeatPatternChanging(string value);
    partial void OnquantityTiming_IntervalRepeatPatternChanged();
    partial void OnquantityTiming_IntervalExplicitTimeIntervalChanging(string value);
    partial void OnquantityTiming_IntervalExplicitTimeIntervalChanged();
    partial void OnquantityTiming_DurationChanging(string value);
    partial void OnquantityTiming_DurationChanged();
    partial void OnquantityTiming_StartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnquantityTiming_StartTimeChanged();
    partial void OnquantityTiming_EndTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnquantityTiming_EndTimeChanged();
    partial void OnquantityTiming_PriorityChanging(string value);
    partial void OnquantityTiming_PriorityChanged();
    partial void OnquantityTiming_ConditionChanging(string value);
    partial void OnquantityTiming_ConditionChanged();
    partial void OnquantityTiming_TextChanging(string value);
    partial void OnquantityTiming_TextChanged();
    partial void OnorderingProviderIdChanging(string value);
    partial void OnorderingProviderIdChanged();
    partial void OnorderingProviderNameChanging(string value);
    partial void OnorderingProviderNameChanged();
    partial void Onprescription_RequestedGiveCode_IdentifierChanging(string value);
    partial void Onprescription_RequestedGiveCode_IdentifierChanged();
    partial void Onprescription_RequestedGiveCode_TextChanging(string value);
    partial void Onprescription_RequestedGiveCode_TextChanged();
    partial void Onprescription_RequestedGiveCode_NameOfCodingSystemChanging(string value);
    partial void Onprescription_RequestedGiveCode_NameOfCodingSystemChanged();
    partial void Onprescription_RequestedGiveCode_AlternateTextChanging(string value);
    partial void Onprescription_RequestedGiveCode_AlternateTextChanged();
    partial void Onprescription_MinimumRequestedGiveAmountChanging(string value);
    partial void Onprescription_MinimumRequestedGiveAmountChanged();
    partial void Onprescription_MaximumRequestedGiveAmountChanging(string value);
    partial void Onprescription_MaximumRequestedGiveAmountChanged();
    partial void Onprescription_NumberRefillsChanging(string value);
    partial void Onprescription_NumberRefillsChanged();
    partial void Onprescription_RequestedGivePerTimeUnitChanging(string value);
    partial void Onprescription_RequestedGivePerTimeUnitChanged();
    partial void Onprescription_RequestedGiveRateAmountChanging(string value);
    partial void Onprescription_RequestedGiveRateAmountChanged();
    partial void Onprescription_RequestedGiveRateUnitsChanging(string value);
    partial void Onprescription_RequestedGiveRateUnitsChanged();
    partial void Onprescription_RXR_RouteChanging(string value);
    partial void Onprescription_RXR_RouteChanged();
    partial void Onprescription_RXR_SiteChanging(string value);
    partial void Onprescription_RXR_SiteChanged();
    partial void Onprescription_RXR_AdministrationDeviceChanging(string value);
    partial void Onprescription_RXR_AdministrationDeviceChanged();
    partial void Onprescription_RXR_AdministrationMethodChanging(string value);
    partial void Onprescription_RXR_AdministrationMethodChanged();
    partial void Onrxe_GiveUnitsChanging(string value);
    partial void Onrxe_GiveUnitsChanged();
    partial void Onrxe_GiveDosageFormChanging(string value);
    partial void Onrxe_GiveDosageFormChanged();
    partial void Onrxe_MinimumGiveAmountChanging(string value);
    partial void Onrxe_MinimumGiveAmountChanged();
    partial void Onrxe_MaximumGiveAmountChanging(string value);
    partial void Onrxe_MaximumGiveAmountChanged();
    partial void Onrxe_DispenseAmountChanging(string value);
    partial void Onrxe_DispenseAmountChanged();
    partial void Onrxe_DispenseUnitsChanging(string value);
    partial void Onrxe_DispenseUnitsChanged();
    partial void Onrxe_NumberOfRefillsChanging(string value);
    partial void Onrxe_NumberOfRefillsChanged();
    partial void Onrxe_NumberOfRefillsRemainingChanging(string value);
    partial void Onrxe_NumberOfRefillsRemainingChanged();
    partial void Onrxe_NumberOfRefillsDoseDispensedChanging(string value);
    partial void Onrxe_NumberOfRefillsDoseDispensedChanged();
    partial void Onrxe_GivePerTimeUnitChanging(string value);
    partial void Onrxe_GivePerTimeUnitChanged();
    partial void Onrxe_GiveRateAmountChanging(string value);
    partial void Onrxe_GiveRateAmountChanged();
    partial void Onrxe_GiveRateUnitsChanging(string value);
    partial void Onrxe_GiveRateUnitsChanged();
    partial void Onrxe_QuantityTiming_QuantityChanging(string value);
    partial void Onrxe_QuantityTiming_QuantityChanged();
    partial void Onrxe_QuantityTiming_QuantityUnitsChanging(string value);
    partial void Onrxe_QuantityTiming_QuantityUnitsChanged();
    partial void Onrxe_QuantityTiming_IntervalRepeatPatternChanging(string value);
    partial void Onrxe_QuantityTiming_IntervalRepeatPatternChanged();
    partial void Onrxe_QuantityTiming_IntervalExplicitTimeIntervalChanging(string value);
    partial void Onrxe_QuantityTiming_IntervalExplicitTimeIntervalChanged();
    partial void Onrxe_QuantityTiming_DurationChanging(string value);
    partial void Onrxe_QuantityTiming_DurationChanged();
    partial void Onrxe_QuantityTiming_StartTimeChanging(System.Nullable<System.DateTime> value);
    partial void Onrxe_QuantityTiming_StartTimeChanged();
    partial void Onrxe_QuantityTiming_EndTimeChanging(System.Nullable<System.DateTime> value);
    partial void Onrxe_QuantityTiming_EndTimeChanged();
    partial void Onrxe_QuantityTiming_PriorityChanging(string value);
    partial void Onrxe_QuantityTiming_PriorityChanged();
    partial void Onrxe_QuantityTiming_ConditionChanging(string value);
    partial void Onrxe_QuantityTiming_ConditionChanged();
    partial void Onrxe_QuantityTiming_TextChanging(string value);
    partial void Onrxe_QuantityTiming_TextChanged();
    partial void Onrxe_GiveCode_IdentifierChanging(string value);
    partial void Onrxe_GiveCode_IdentifierChanged();
    partial void Onrxe_GiveCode_TextChanging(string value);
    partial void Onrxe_GiveCode_TextChanged();
    partial void Onrxe_GiveCode_NameOfCodingSystemChanging(string value);
    partial void Onrxe_GiveCode_NameOfCodingSystemChanged();
    partial void Onrxe_GiveCode_AlternateTextChanging(string value);
    partial void Onrxe_GiveCode_AlternateTextChanged();
    partial void Onrxe_Pharmisist_IdentifierChanging(string value);
    partial void Onrxe_Pharmisist_IdentifierChanged();
    partial void Onrxe_Pharmisist_NameChanging(string value);
    partial void Onrxe_Pharmisist_NameChanged();
    partial void Onrxr_RouteChanging(string value);
    partial void Onrxr_RouteChanged();
    partial void Onrxr_SiteChanging(string value);
    partial void Onrxr_SiteChanged();
    partial void Onrxr_AdministrationDeviceChanging(string value);
    partial void Onrxr_AdministrationDeviceChanged();
    partial void Onrxr_AdministrationMethodChanging(string value);
    partial void Onrxr_AdministrationMethodChanged();
    #endregion
		
		public DtsRdeOrdersStdArchive()
		{
			this._DtsRdeOrdersRxcStdArchives = new EntitySet<DtsRdeOrdersRxcStdArchive>(new Action<DtsRdeOrdersRxcStdArchive>(this.attach_DtsRdeOrdersRxcStdArchives), new Action<DtsRdeOrdersRxcStdArchive>(this.detach_DtsRdeOrdersRxcStdArchives));
			this._DtsRdeStdArchive = default(EntityRef<DtsRdeStdArchive>);
			OnCreated();
		}
		
		[Column(Storage="_headerRow_tk", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal headerRow_tk
		{
			get
			{
				return this._headerRow_tk;
			}
			set
			{
				if ((this._headerRow_tk != value))
				{
					if (this._DtsRdeStdArchive.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnheaderRow_tkChanging(value);
					this.SendPropertyChanging();
					this._headerRow_tk = value;
					this.SendPropertyChanged("headerRow_tk");
					this.OnheaderRow_tkChanged();
				}
			}
		}
		
		[Column(Storage="_orderRow_tk", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int orderRow_tk
		{
			get
			{
				return this._orderRow_tk;
			}
			set
			{
				if ((this._orderRow_tk != value))
				{
					this.OnorderRow_tkChanging(value);
					this.SendPropertyChanging();
					this._orderRow_tk = value;
					this.SendPropertyChanged("orderRow_tk");
					this.OnorderRow_tkChanged();
				}
			}
		}
		
		[Column(Storage="_orderControl", DbType="VarChar(50)")]
		public string orderControl
		{
			get
			{
				return this._orderControl;
			}
			set
			{
				if ((this._orderControl != value))
				{
					this.OnorderControlChanging(value);
					this.SendPropertyChanging();
					this._orderControl = value;
					this.SendPropertyChanged("orderControl");
					this.OnorderControlChanged();
				}
			}
		}
		
		[Column(Storage="_orderEffectiveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> orderEffectiveDate
		{
			get
			{
				return this._orderEffectiveDate;
			}
			set
			{
				if ((this._orderEffectiveDate != value))
				{
					this.OnorderEffectiveDateChanging(value);
					this.SendPropertyChanging();
					this._orderEffectiveDate = value;
					this.SendPropertyChanged("orderEffectiveDate");
					this.OnorderEffectiveDateChanged();
				}
			}
		}
		
		[Column(Storage="_transactionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> transactionDate
		{
			get
			{
				return this._transactionDate;
			}
			set
			{
				if ((this._transactionDate != value))
				{
					this.OntransactionDateChanging(value);
					this.SendPropertyChanging();
					this._transactionDate = value;
					this.SendPropertyChanged("transactionDate");
					this.OntransactionDateChanged();
				}
			}
		}
		
		[Column(Storage="_prescriptionNumber", DbType="VarChar(50)")]
		public string prescriptionNumber
		{
			get
			{
				return this._prescriptionNumber;
			}
			set
			{
				if ((this._prescriptionNumber != value))
				{
					this.OnprescriptionNumberChanging(value);
					this.SendPropertyChanging();
					this._prescriptionNumber = value;
					this.SendPropertyChanged("prescriptionNumber");
					this.OnprescriptionNumberChanged();
				}
			}
		}
		
		[Column(Storage="_placerOrderNumber", DbType="VarChar(50)")]
		public string placerOrderNumber
		{
			get
			{
				return this._placerOrderNumber;
			}
			set
			{
				if ((this._placerOrderNumber != value))
				{
					this.OnplacerOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._placerOrderNumber = value;
					this.SendPropertyChanged("placerOrderNumber");
					this.OnplacerOrderNumberChanged();
				}
			}
		}
		
		[Column(Storage="_fillerOrderNumber", DbType="VarChar(50)")]
		public string fillerOrderNumber
		{
			get
			{
				return this._fillerOrderNumber;
			}
			set
			{
				if ((this._fillerOrderNumber != value))
				{
					this.OnfillerOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._fillerOrderNumber = value;
					this.SendPropertyChanged("fillerOrderNumber");
					this.OnfillerOrderNumberChanged();
				}
			}
		}
		
		[Column(Storage="_parentPlacerOrderNumber", DbType="VarChar(50)")]
		public string parentPlacerOrderNumber
		{
			get
			{
				return this._parentPlacerOrderNumber;
			}
			set
			{
				if ((this._parentPlacerOrderNumber != value))
				{
					this.OnparentPlacerOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._parentPlacerOrderNumber = value;
					this.SendPropertyChanged("parentPlacerOrderNumber");
					this.OnparentPlacerOrderNumberChanged();
				}
			}
		}
		
		[Column(Storage="_parentFillerOrderNumber", DbType="VarChar(50)")]
		public string parentFillerOrderNumber
		{
			get
			{
				return this._parentFillerOrderNumber;
			}
			set
			{
				if ((this._parentFillerOrderNumber != value))
				{
					this.OnparentFillerOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._parentFillerOrderNumber = value;
					this.SendPropertyChanged("parentFillerOrderNumber");
					this.OnparentFillerOrderNumberChanged();
				}
			}
		}
		
		[Column(Storage="_quantityTiming_Quantity", DbType="VarChar(50)")]
		public string quantityTiming_Quantity
		{
			get
			{
				return this._quantityTiming_Quantity;
			}
			set
			{
				if ((this._quantityTiming_Quantity != value))
				{
					this.OnquantityTiming_QuantityChanging(value);
					this.SendPropertyChanging();
					this._quantityTiming_Quantity = value;
					this.SendPropertyChanged("quantityTiming_Quantity");
					this.OnquantityTiming_QuantityChanged();
				}
			}
		}
		
		[Column(Storage="_quantityTiming_QuantityUnits", DbType="VarChar(50)")]
		public string quantityTiming_QuantityUnits
		{
			get
			{
				return this._quantityTiming_QuantityUnits;
			}
			set
			{
				if ((this._quantityTiming_QuantityUnits != value))
				{
					this.OnquantityTiming_QuantityUnitsChanging(value);
					this.SendPropertyChanging();
					this._quantityTiming_QuantityUnits = value;
					this.SendPropertyChanged("quantityTiming_QuantityUnits");
					this.OnquantityTiming_QuantityUnitsChanged();
				}
			}
		}
		
		[Column(Storage="_quantityTiming_IntervalRepeatPattern", DbType="VarChar(50)")]
		public string quantityTiming_IntervalRepeatPattern
		{
			get
			{
				return this._quantityTiming_IntervalRepeatPattern;
			}
			set
			{
				if ((this._quantityTiming_IntervalRepeatPattern != value))
				{
					this.OnquantityTiming_IntervalRepeatPatternChanging(value);
					this.SendPropertyChanging();
					this._quantityTiming_IntervalRepeatPattern = value;
					this.SendPropertyChanged("quantityTiming_IntervalRepeatPattern");
					this.OnquantityTiming_IntervalRepeatPatternChanged();
				}
			}
		}
		
		[Column(Storage="_quantityTiming_IntervalExplicitTimeInterval", DbType="VarChar(150)")]
		public string quantityTiming_IntervalExplicitTimeInterval
		{
			get
			{
				return this._quantityTiming_IntervalExplicitTimeInterval;
			}
			set
			{
				if ((this._quantityTiming_IntervalExplicitTimeInterval != value))
				{
					this.OnquantityTiming_IntervalExplicitTimeIntervalChanging(value);
					this.SendPropertyChanging();
					this._quantityTiming_IntervalExplicitTimeInterval = value;
					this.SendPropertyChanged("quantityTiming_IntervalExplicitTimeInterval");
					this.OnquantityTiming_IntervalExplicitTimeIntervalChanged();
				}
			}
		}
		
		[Column(Storage="_quantityTiming_Duration", DbType="VarChar(50)")]
		public string quantityTiming_Duration
		{
			get
			{
				return this._quantityTiming_Duration;
			}
			set
			{
				if ((this._quantityTiming_Duration != value))
				{
					this.OnquantityTiming_DurationChanging(value);
					this.SendPropertyChanging();
					this._quantityTiming_Duration = value;
					this.SendPropertyChanged("quantityTiming_Duration");
					this.OnquantityTiming_DurationChanged();
				}
			}
		}
		
		[Column(Storage="_quantityTiming_StartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> quantityTiming_StartTime
		{
			get
			{
				return this._quantityTiming_StartTime;
			}
			set
			{
				if ((this._quantityTiming_StartTime != value))
				{
					this.OnquantityTiming_StartTimeChanging(value);
					this.SendPropertyChanging();
					this._quantityTiming_StartTime = value;
					this.SendPropertyChanged("quantityTiming_StartTime");
					this.OnquantityTiming_StartTimeChanged();
				}
			}
		}
		
		[Column(Storage="_quantityTiming_EndTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> quantityTiming_EndTime
		{
			get
			{
				return this._quantityTiming_EndTime;
			}
			set
			{
				if ((this._quantityTiming_EndTime != value))
				{
					this.OnquantityTiming_EndTimeChanging(value);
					this.SendPropertyChanging();
					this._quantityTiming_EndTime = value;
					this.SendPropertyChanged("quantityTiming_EndTime");
					this.OnquantityTiming_EndTimeChanged();
				}
			}
		}
		
		[Column(Storage="_quantityTiming_Priority", DbType="VarChar(50)")]
		public string quantityTiming_Priority
		{
			get
			{
				return this._quantityTiming_Priority;
			}
			set
			{
				if ((this._quantityTiming_Priority != value))
				{
					this.OnquantityTiming_PriorityChanging(value);
					this.SendPropertyChanging();
					this._quantityTiming_Priority = value;
					this.SendPropertyChanged("quantityTiming_Priority");
					this.OnquantityTiming_PriorityChanged();
				}
			}
		}
		
		[Column(Storage="_quantityTiming_Condition", DbType="VarChar(50)")]
		public string quantityTiming_Condition
		{
			get
			{
				return this._quantityTiming_Condition;
			}
			set
			{
				if ((this._quantityTiming_Condition != value))
				{
					this.OnquantityTiming_ConditionChanging(value);
					this.SendPropertyChanging();
					this._quantityTiming_Condition = value;
					this.SendPropertyChanged("quantityTiming_Condition");
					this.OnquantityTiming_ConditionChanged();
				}
			}
		}
		
		[Column(Storage="_quantityTiming_Text", DbType="VarChar(50)")]
		public string quantityTiming_Text
		{
			get
			{
				return this._quantityTiming_Text;
			}
			set
			{
				if ((this._quantityTiming_Text != value))
				{
					this.OnquantityTiming_TextChanging(value);
					this.SendPropertyChanging();
					this._quantityTiming_Text = value;
					this.SendPropertyChanged("quantityTiming_Text");
					this.OnquantityTiming_TextChanged();
				}
			}
		}
		
		[Column(Storage="_orderingProviderId", DbType="VarChar(50)")]
		public string orderingProviderId
		{
			get
			{
				return this._orderingProviderId;
			}
			set
			{
				if ((this._orderingProviderId != value))
				{
					this.OnorderingProviderIdChanging(value);
					this.SendPropertyChanging();
					this._orderingProviderId = value;
					this.SendPropertyChanged("orderingProviderId");
					this.OnorderingProviderIdChanged();
				}
			}
		}
		
		[Column(Storage="_orderingProviderName", DbType="VarChar(50)")]
		public string orderingProviderName
		{
			get
			{
				return this._orderingProviderName;
			}
			set
			{
				if ((this._orderingProviderName != value))
				{
					this.OnorderingProviderNameChanging(value);
					this.SendPropertyChanging();
					this._orderingProviderName = value;
					this.SendPropertyChanged("orderingProviderName");
					this.OnorderingProviderNameChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_RequestedGiveCode_Identifier", DbType="VarChar(50)")]
		public string prescription_RequestedGiveCode_Identifier
		{
			get
			{
				return this._prescription_RequestedGiveCode_Identifier;
			}
			set
			{
				if ((this._prescription_RequestedGiveCode_Identifier != value))
				{
					this.Onprescription_RequestedGiveCode_IdentifierChanging(value);
					this.SendPropertyChanging();
					this._prescription_RequestedGiveCode_Identifier = value;
					this.SendPropertyChanged("prescription_RequestedGiveCode_Identifier");
					this.Onprescription_RequestedGiveCode_IdentifierChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_RequestedGiveCode_Text", DbType="VarChar(50)")]
		public string prescription_RequestedGiveCode_Text
		{
			get
			{
				return this._prescription_RequestedGiveCode_Text;
			}
			set
			{
				if ((this._prescription_RequestedGiveCode_Text != value))
				{
					this.Onprescription_RequestedGiveCode_TextChanging(value);
					this.SendPropertyChanging();
					this._prescription_RequestedGiveCode_Text = value;
					this.SendPropertyChanged("prescription_RequestedGiveCode_Text");
					this.Onprescription_RequestedGiveCode_TextChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_RequestedGiveCode_NameOfCodingSystem", DbType="VarChar(50)")]
		public string prescription_RequestedGiveCode_NameOfCodingSystem
		{
			get
			{
				return this._prescription_RequestedGiveCode_NameOfCodingSystem;
			}
			set
			{
				if ((this._prescription_RequestedGiveCode_NameOfCodingSystem != value))
				{
					this.Onprescription_RequestedGiveCode_NameOfCodingSystemChanging(value);
					this.SendPropertyChanging();
					this._prescription_RequestedGiveCode_NameOfCodingSystem = value;
					this.SendPropertyChanged("prescription_RequestedGiveCode_NameOfCodingSystem");
					this.Onprescription_RequestedGiveCode_NameOfCodingSystemChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_RequestedGiveCode_AlternateText", DbType="VarChar(50)")]
		public string prescription_RequestedGiveCode_AlternateText
		{
			get
			{
				return this._prescription_RequestedGiveCode_AlternateText;
			}
			set
			{
				if ((this._prescription_RequestedGiveCode_AlternateText != value))
				{
					this.Onprescription_RequestedGiveCode_AlternateTextChanging(value);
					this.SendPropertyChanging();
					this._prescription_RequestedGiveCode_AlternateText = value;
					this.SendPropertyChanged("prescription_RequestedGiveCode_AlternateText");
					this.Onprescription_RequestedGiveCode_AlternateTextChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_MinimumRequestedGiveAmount", DbType="VarChar(50)")]
		public string prescription_MinimumRequestedGiveAmount
		{
			get
			{
				return this._prescription_MinimumRequestedGiveAmount;
			}
			set
			{
				if ((this._prescription_MinimumRequestedGiveAmount != value))
				{
					this.Onprescription_MinimumRequestedGiveAmountChanging(value);
					this.SendPropertyChanging();
					this._prescription_MinimumRequestedGiveAmount = value;
					this.SendPropertyChanged("prescription_MinimumRequestedGiveAmount");
					this.Onprescription_MinimumRequestedGiveAmountChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_MaximumRequestedGiveAmount", DbType="VarChar(50)")]
		public string prescription_MaximumRequestedGiveAmount
		{
			get
			{
				return this._prescription_MaximumRequestedGiveAmount;
			}
			set
			{
				if ((this._prescription_MaximumRequestedGiveAmount != value))
				{
					this.Onprescription_MaximumRequestedGiveAmountChanging(value);
					this.SendPropertyChanging();
					this._prescription_MaximumRequestedGiveAmount = value;
					this.SendPropertyChanged("prescription_MaximumRequestedGiveAmount");
					this.Onprescription_MaximumRequestedGiveAmountChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_NumberRefills", DbType="VarChar(50)")]
		public string prescription_NumberRefills
		{
			get
			{
				return this._prescription_NumberRefills;
			}
			set
			{
				if ((this._prescription_NumberRefills != value))
				{
					this.Onprescription_NumberRefillsChanging(value);
					this.SendPropertyChanging();
					this._prescription_NumberRefills = value;
					this.SendPropertyChanged("prescription_NumberRefills");
					this.Onprescription_NumberRefillsChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_RequestedGivePerTimeUnit", DbType="VarChar(50)")]
		public string prescription_RequestedGivePerTimeUnit
		{
			get
			{
				return this._prescription_RequestedGivePerTimeUnit;
			}
			set
			{
				if ((this._prescription_RequestedGivePerTimeUnit != value))
				{
					this.Onprescription_RequestedGivePerTimeUnitChanging(value);
					this.SendPropertyChanging();
					this._prescription_RequestedGivePerTimeUnit = value;
					this.SendPropertyChanged("prescription_RequestedGivePerTimeUnit");
					this.Onprescription_RequestedGivePerTimeUnitChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_RequestedGiveRateAmount", DbType="VarChar(50)")]
		public string prescription_RequestedGiveRateAmount
		{
			get
			{
				return this._prescription_RequestedGiveRateAmount;
			}
			set
			{
				if ((this._prescription_RequestedGiveRateAmount != value))
				{
					this.Onprescription_RequestedGiveRateAmountChanging(value);
					this.SendPropertyChanging();
					this._prescription_RequestedGiveRateAmount = value;
					this.SendPropertyChanged("prescription_RequestedGiveRateAmount");
					this.Onprescription_RequestedGiveRateAmountChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_RequestedGiveRateUnits", DbType="VarChar(50)")]
		public string prescription_RequestedGiveRateUnits
		{
			get
			{
				return this._prescription_RequestedGiveRateUnits;
			}
			set
			{
				if ((this._prescription_RequestedGiveRateUnits != value))
				{
					this.Onprescription_RequestedGiveRateUnitsChanging(value);
					this.SendPropertyChanging();
					this._prescription_RequestedGiveRateUnits = value;
					this.SendPropertyChanged("prescription_RequestedGiveRateUnits");
					this.Onprescription_RequestedGiveRateUnitsChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_RXR_Route", DbType="VarChar(50)")]
		public string prescription_RXR_Route
		{
			get
			{
				return this._prescription_RXR_Route;
			}
			set
			{
				if ((this._prescription_RXR_Route != value))
				{
					this.Onprescription_RXR_RouteChanging(value);
					this.SendPropertyChanging();
					this._prescription_RXR_Route = value;
					this.SendPropertyChanged("prescription_RXR_Route");
					this.Onprescription_RXR_RouteChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_RXR_Site", DbType="VarChar(50)")]
		public string prescription_RXR_Site
		{
			get
			{
				return this._prescription_RXR_Site;
			}
			set
			{
				if ((this._prescription_RXR_Site != value))
				{
					this.Onprescription_RXR_SiteChanging(value);
					this.SendPropertyChanging();
					this._prescription_RXR_Site = value;
					this.SendPropertyChanged("prescription_RXR_Site");
					this.Onprescription_RXR_SiteChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_RXR_AdministrationDevice", DbType="VarChar(50)")]
		public string prescription_RXR_AdministrationDevice
		{
			get
			{
				return this._prescription_RXR_AdministrationDevice;
			}
			set
			{
				if ((this._prescription_RXR_AdministrationDevice != value))
				{
					this.Onprescription_RXR_AdministrationDeviceChanging(value);
					this.SendPropertyChanging();
					this._prescription_RXR_AdministrationDevice = value;
					this.SendPropertyChanged("prescription_RXR_AdministrationDevice");
					this.Onprescription_RXR_AdministrationDeviceChanged();
				}
			}
		}
		
		[Column(Storage="_prescription_RXR_AdministrationMethod", DbType="VarChar(50)")]
		public string prescription_RXR_AdministrationMethod
		{
			get
			{
				return this._prescription_RXR_AdministrationMethod;
			}
			set
			{
				if ((this._prescription_RXR_AdministrationMethod != value))
				{
					this.Onprescription_RXR_AdministrationMethodChanging(value);
					this.SendPropertyChanging();
					this._prescription_RXR_AdministrationMethod = value;
					this.SendPropertyChanged("prescription_RXR_AdministrationMethod");
					this.Onprescription_RXR_AdministrationMethodChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_GiveUnits", DbType="VarChar(50)")]
		public string rxe_GiveUnits
		{
			get
			{
				return this._rxe_GiveUnits;
			}
			set
			{
				if ((this._rxe_GiveUnits != value))
				{
					this.Onrxe_GiveUnitsChanging(value);
					this.SendPropertyChanging();
					this._rxe_GiveUnits = value;
					this.SendPropertyChanged("rxe_GiveUnits");
					this.Onrxe_GiveUnitsChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_GiveDosageForm", DbType="VarChar(50)")]
		public string rxe_GiveDosageForm
		{
			get
			{
				return this._rxe_GiveDosageForm;
			}
			set
			{
				if ((this._rxe_GiveDosageForm != value))
				{
					this.Onrxe_GiveDosageFormChanging(value);
					this.SendPropertyChanging();
					this._rxe_GiveDosageForm = value;
					this.SendPropertyChanged("rxe_GiveDosageForm");
					this.Onrxe_GiveDosageFormChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_MinimumGiveAmount", DbType="VarChar(50)")]
		public string rxe_MinimumGiveAmount
		{
			get
			{
				return this._rxe_MinimumGiveAmount;
			}
			set
			{
				if ((this._rxe_MinimumGiveAmount != value))
				{
					this.Onrxe_MinimumGiveAmountChanging(value);
					this.SendPropertyChanging();
					this._rxe_MinimumGiveAmount = value;
					this.SendPropertyChanged("rxe_MinimumGiveAmount");
					this.Onrxe_MinimumGiveAmountChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_MaximumGiveAmount", DbType="VarChar(50)")]
		public string rxe_MaximumGiveAmount
		{
			get
			{
				return this._rxe_MaximumGiveAmount;
			}
			set
			{
				if ((this._rxe_MaximumGiveAmount != value))
				{
					this.Onrxe_MaximumGiveAmountChanging(value);
					this.SendPropertyChanging();
					this._rxe_MaximumGiveAmount = value;
					this.SendPropertyChanged("rxe_MaximumGiveAmount");
					this.Onrxe_MaximumGiveAmountChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_DispenseAmount", DbType="VarChar(50)")]
		public string rxe_DispenseAmount
		{
			get
			{
				return this._rxe_DispenseAmount;
			}
			set
			{
				if ((this._rxe_DispenseAmount != value))
				{
					this.Onrxe_DispenseAmountChanging(value);
					this.SendPropertyChanging();
					this._rxe_DispenseAmount = value;
					this.SendPropertyChanged("rxe_DispenseAmount");
					this.Onrxe_DispenseAmountChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_DispenseUnits", DbType="VarChar(50)")]
		public string rxe_DispenseUnits
		{
			get
			{
				return this._rxe_DispenseUnits;
			}
			set
			{
				if ((this._rxe_DispenseUnits != value))
				{
					this.Onrxe_DispenseUnitsChanging(value);
					this.SendPropertyChanging();
					this._rxe_DispenseUnits = value;
					this.SendPropertyChanged("rxe_DispenseUnits");
					this.Onrxe_DispenseUnitsChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_NumberOfRefills", DbType="VarChar(50)")]
		public string rxe_NumberOfRefills
		{
			get
			{
				return this._rxe_NumberOfRefills;
			}
			set
			{
				if ((this._rxe_NumberOfRefills != value))
				{
					this.Onrxe_NumberOfRefillsChanging(value);
					this.SendPropertyChanging();
					this._rxe_NumberOfRefills = value;
					this.SendPropertyChanged("rxe_NumberOfRefills");
					this.Onrxe_NumberOfRefillsChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_NumberOfRefillsRemaining", DbType="VarChar(50)")]
		public string rxe_NumberOfRefillsRemaining
		{
			get
			{
				return this._rxe_NumberOfRefillsRemaining;
			}
			set
			{
				if ((this._rxe_NumberOfRefillsRemaining != value))
				{
					this.Onrxe_NumberOfRefillsRemainingChanging(value);
					this.SendPropertyChanging();
					this._rxe_NumberOfRefillsRemaining = value;
					this.SendPropertyChanged("rxe_NumberOfRefillsRemaining");
					this.Onrxe_NumberOfRefillsRemainingChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_NumberOfRefillsDoseDispensed", DbType="VarChar(50)")]
		public string rxe_NumberOfRefillsDoseDispensed
		{
			get
			{
				return this._rxe_NumberOfRefillsDoseDispensed;
			}
			set
			{
				if ((this._rxe_NumberOfRefillsDoseDispensed != value))
				{
					this.Onrxe_NumberOfRefillsDoseDispensedChanging(value);
					this.SendPropertyChanging();
					this._rxe_NumberOfRefillsDoseDispensed = value;
					this.SendPropertyChanged("rxe_NumberOfRefillsDoseDispensed");
					this.Onrxe_NumberOfRefillsDoseDispensedChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_GivePerTimeUnit", DbType="VarChar(50)")]
		public string rxe_GivePerTimeUnit
		{
			get
			{
				return this._rxe_GivePerTimeUnit;
			}
			set
			{
				if ((this._rxe_GivePerTimeUnit != value))
				{
					this.Onrxe_GivePerTimeUnitChanging(value);
					this.SendPropertyChanging();
					this._rxe_GivePerTimeUnit = value;
					this.SendPropertyChanged("rxe_GivePerTimeUnit");
					this.Onrxe_GivePerTimeUnitChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_GiveRateAmount", DbType="VarChar(50)")]
		public string rxe_GiveRateAmount
		{
			get
			{
				return this._rxe_GiveRateAmount;
			}
			set
			{
				if ((this._rxe_GiveRateAmount != value))
				{
					this.Onrxe_GiveRateAmountChanging(value);
					this.SendPropertyChanging();
					this._rxe_GiveRateAmount = value;
					this.SendPropertyChanged("rxe_GiveRateAmount");
					this.Onrxe_GiveRateAmountChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_GiveRateUnits", DbType="VarChar(50)")]
		public string rxe_GiveRateUnits
		{
			get
			{
				return this._rxe_GiveRateUnits;
			}
			set
			{
				if ((this._rxe_GiveRateUnits != value))
				{
					this.Onrxe_GiveRateUnitsChanging(value);
					this.SendPropertyChanging();
					this._rxe_GiveRateUnits = value;
					this.SendPropertyChanged("rxe_GiveRateUnits");
					this.Onrxe_GiveRateUnitsChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_QuantityTiming_Quantity", DbType="VarChar(50)")]
		public string rxe_QuantityTiming_Quantity
		{
			get
			{
				return this._rxe_QuantityTiming_Quantity;
			}
			set
			{
				if ((this._rxe_QuantityTiming_Quantity != value))
				{
					this.Onrxe_QuantityTiming_QuantityChanging(value);
					this.SendPropertyChanging();
					this._rxe_QuantityTiming_Quantity = value;
					this.SendPropertyChanged("rxe_QuantityTiming_Quantity");
					this.Onrxe_QuantityTiming_QuantityChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_QuantityTiming_QuantityUnits", DbType="VarChar(50)")]
		public string rxe_QuantityTiming_QuantityUnits
		{
			get
			{
				return this._rxe_QuantityTiming_QuantityUnits;
			}
			set
			{
				if ((this._rxe_QuantityTiming_QuantityUnits != value))
				{
					this.Onrxe_QuantityTiming_QuantityUnitsChanging(value);
					this.SendPropertyChanging();
					this._rxe_QuantityTiming_QuantityUnits = value;
					this.SendPropertyChanged("rxe_QuantityTiming_QuantityUnits");
					this.Onrxe_QuantityTiming_QuantityUnitsChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_QuantityTiming_IntervalRepeatPattern", DbType="VarChar(50)")]
		public string rxe_QuantityTiming_IntervalRepeatPattern
		{
			get
			{
				return this._rxe_QuantityTiming_IntervalRepeatPattern;
			}
			set
			{
				if ((this._rxe_QuantityTiming_IntervalRepeatPattern != value))
				{
					this.Onrxe_QuantityTiming_IntervalRepeatPatternChanging(value);
					this.SendPropertyChanging();
					this._rxe_QuantityTiming_IntervalRepeatPattern = value;
					this.SendPropertyChanged("rxe_QuantityTiming_IntervalRepeatPattern");
					this.Onrxe_QuantityTiming_IntervalRepeatPatternChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_QuantityTiming_IntervalExplicitTimeInterval", DbType="VarChar(150)")]
		public string rxe_QuantityTiming_IntervalExplicitTimeInterval
		{
			get
			{
				return this._rxe_QuantityTiming_IntervalExplicitTimeInterval;
			}
			set
			{
				if ((this._rxe_QuantityTiming_IntervalExplicitTimeInterval != value))
				{
					this.Onrxe_QuantityTiming_IntervalExplicitTimeIntervalChanging(value);
					this.SendPropertyChanging();
					this._rxe_QuantityTiming_IntervalExplicitTimeInterval = value;
					this.SendPropertyChanged("rxe_QuantityTiming_IntervalExplicitTimeInterval");
					this.Onrxe_QuantityTiming_IntervalExplicitTimeIntervalChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_QuantityTiming_Duration", DbType="VarChar(50)")]
		public string rxe_QuantityTiming_Duration
		{
			get
			{
				return this._rxe_QuantityTiming_Duration;
			}
			set
			{
				if ((this._rxe_QuantityTiming_Duration != value))
				{
					this.Onrxe_QuantityTiming_DurationChanging(value);
					this.SendPropertyChanging();
					this._rxe_QuantityTiming_Duration = value;
					this.SendPropertyChanged("rxe_QuantityTiming_Duration");
					this.Onrxe_QuantityTiming_DurationChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_QuantityTiming_StartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> rxe_QuantityTiming_StartTime
		{
			get
			{
				return this._rxe_QuantityTiming_StartTime;
			}
			set
			{
				if ((this._rxe_QuantityTiming_StartTime != value))
				{
					this.Onrxe_QuantityTiming_StartTimeChanging(value);
					this.SendPropertyChanging();
					this._rxe_QuantityTiming_StartTime = value;
					this.SendPropertyChanged("rxe_QuantityTiming_StartTime");
					this.Onrxe_QuantityTiming_StartTimeChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_QuantityTiming_EndTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> rxe_QuantityTiming_EndTime
		{
			get
			{
				return this._rxe_QuantityTiming_EndTime;
			}
			set
			{
				if ((this._rxe_QuantityTiming_EndTime != value))
				{
					this.Onrxe_QuantityTiming_EndTimeChanging(value);
					this.SendPropertyChanging();
					this._rxe_QuantityTiming_EndTime = value;
					this.SendPropertyChanged("rxe_QuantityTiming_EndTime");
					this.Onrxe_QuantityTiming_EndTimeChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_QuantityTiming_Priority", DbType="VarChar(50)")]
		public string rxe_QuantityTiming_Priority
		{
			get
			{
				return this._rxe_QuantityTiming_Priority;
			}
			set
			{
				if ((this._rxe_QuantityTiming_Priority != value))
				{
					this.Onrxe_QuantityTiming_PriorityChanging(value);
					this.SendPropertyChanging();
					this._rxe_QuantityTiming_Priority = value;
					this.SendPropertyChanged("rxe_QuantityTiming_Priority");
					this.Onrxe_QuantityTiming_PriorityChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_QuantityTiming_Condition", DbType="VarChar(50)")]
		public string rxe_QuantityTiming_Condition
		{
			get
			{
				return this._rxe_QuantityTiming_Condition;
			}
			set
			{
				if ((this._rxe_QuantityTiming_Condition != value))
				{
					this.Onrxe_QuantityTiming_ConditionChanging(value);
					this.SendPropertyChanging();
					this._rxe_QuantityTiming_Condition = value;
					this.SendPropertyChanged("rxe_QuantityTiming_Condition");
					this.Onrxe_QuantityTiming_ConditionChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_QuantityTiming_Text", DbType="VarChar(50)")]
		public string rxe_QuantityTiming_Text
		{
			get
			{
				return this._rxe_QuantityTiming_Text;
			}
			set
			{
				if ((this._rxe_QuantityTiming_Text != value))
				{
					this.Onrxe_QuantityTiming_TextChanging(value);
					this.SendPropertyChanging();
					this._rxe_QuantityTiming_Text = value;
					this.SendPropertyChanged("rxe_QuantityTiming_Text");
					this.Onrxe_QuantityTiming_TextChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_GiveCode_Identifier", DbType="VarChar(50)")]
		public string rxe_GiveCode_Identifier
		{
			get
			{
				return this._rxe_GiveCode_Identifier;
			}
			set
			{
				if ((this._rxe_GiveCode_Identifier != value))
				{
					this.Onrxe_GiveCode_IdentifierChanging(value);
					this.SendPropertyChanging();
					this._rxe_GiveCode_Identifier = value;
					this.SendPropertyChanged("rxe_GiveCode_Identifier");
					this.Onrxe_GiveCode_IdentifierChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_GiveCode_Text", DbType="VarChar(50)")]
		public string rxe_GiveCode_Text
		{
			get
			{
				return this._rxe_GiveCode_Text;
			}
			set
			{
				if ((this._rxe_GiveCode_Text != value))
				{
					this.Onrxe_GiveCode_TextChanging(value);
					this.SendPropertyChanging();
					this._rxe_GiveCode_Text = value;
					this.SendPropertyChanged("rxe_GiveCode_Text");
					this.Onrxe_GiveCode_TextChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_GiveCode_NameOfCodingSystem", DbType="VarChar(50)")]
		public string rxe_GiveCode_NameOfCodingSystem
		{
			get
			{
				return this._rxe_GiveCode_NameOfCodingSystem;
			}
			set
			{
				if ((this._rxe_GiveCode_NameOfCodingSystem != value))
				{
					this.Onrxe_GiveCode_NameOfCodingSystemChanging(value);
					this.SendPropertyChanging();
					this._rxe_GiveCode_NameOfCodingSystem = value;
					this.SendPropertyChanged("rxe_GiveCode_NameOfCodingSystem");
					this.Onrxe_GiveCode_NameOfCodingSystemChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_GiveCode_AlternateText", DbType="VarChar(50)")]
		public string rxe_GiveCode_AlternateText
		{
			get
			{
				return this._rxe_GiveCode_AlternateText;
			}
			set
			{
				if ((this._rxe_GiveCode_AlternateText != value))
				{
					this.Onrxe_GiveCode_AlternateTextChanging(value);
					this.SendPropertyChanging();
					this._rxe_GiveCode_AlternateText = value;
					this.SendPropertyChanged("rxe_GiveCode_AlternateText");
					this.Onrxe_GiveCode_AlternateTextChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_Pharmisist_Identifier", DbType="VarChar(50)")]
		public string rxe_Pharmisist_Identifier
		{
			get
			{
				return this._rxe_Pharmisist_Identifier;
			}
			set
			{
				if ((this._rxe_Pharmisist_Identifier != value))
				{
					this.Onrxe_Pharmisist_IdentifierChanging(value);
					this.SendPropertyChanging();
					this._rxe_Pharmisist_Identifier = value;
					this.SendPropertyChanged("rxe_Pharmisist_Identifier");
					this.Onrxe_Pharmisist_IdentifierChanged();
				}
			}
		}
		
		[Column(Storage="_rxe_Pharmisist_Name", DbType="VarChar(50)")]
		public string rxe_Pharmisist_Name
		{
			get
			{
				return this._rxe_Pharmisist_Name;
			}
			set
			{
				if ((this._rxe_Pharmisist_Name != value))
				{
					this.Onrxe_Pharmisist_NameChanging(value);
					this.SendPropertyChanging();
					this._rxe_Pharmisist_Name = value;
					this.SendPropertyChanged("rxe_Pharmisist_Name");
					this.Onrxe_Pharmisist_NameChanged();
				}
			}
		}
		
		[Column(Storage="_rxr_Route", DbType="VarChar(50)")]
		public string rxr_Route
		{
			get
			{
				return this._rxr_Route;
			}
			set
			{
				if ((this._rxr_Route != value))
				{
					this.Onrxr_RouteChanging(value);
					this.SendPropertyChanging();
					this._rxr_Route = value;
					this.SendPropertyChanged("rxr_Route");
					this.Onrxr_RouteChanged();
				}
			}
		}
		
		[Column(Storage="_rxr_Site", DbType="VarChar(50)")]
		public string rxr_Site
		{
			get
			{
				return this._rxr_Site;
			}
			set
			{
				if ((this._rxr_Site != value))
				{
					this.Onrxr_SiteChanging(value);
					this.SendPropertyChanging();
					this._rxr_Site = value;
					this.SendPropertyChanged("rxr_Site");
					this.Onrxr_SiteChanged();
				}
			}
		}
		
		[Column(Storage="_rxr_AdministrationDevice", DbType="VarChar(50)")]
		public string rxr_AdministrationDevice
		{
			get
			{
				return this._rxr_AdministrationDevice;
			}
			set
			{
				if ((this._rxr_AdministrationDevice != value))
				{
					this.Onrxr_AdministrationDeviceChanging(value);
					this.SendPropertyChanging();
					this._rxr_AdministrationDevice = value;
					this.SendPropertyChanged("rxr_AdministrationDevice");
					this.Onrxr_AdministrationDeviceChanged();
				}
			}
		}
		
		[Column(Storage="_rxr_AdministrationMethod", DbType="VarChar(50)")]
		public string rxr_AdministrationMethod
		{
			get
			{
				return this._rxr_AdministrationMethod;
			}
			set
			{
				if ((this._rxr_AdministrationMethod != value))
				{
					this.Onrxr_AdministrationMethodChanging(value);
					this.SendPropertyChanging();
					this._rxr_AdministrationMethod = value;
					this.SendPropertyChanged("rxr_AdministrationMethod");
					this.Onrxr_AdministrationMethodChanged();
				}
			}
		}
		
		[Association(Name="DtsRdeOrdersStdArchive_DtsRdeOrdersRxcStdArchive", Storage="_DtsRdeOrdersRxcStdArchives", ThisKey="headerRow_tk,orderRow_tk", OtherKey="headerRow_tk,orderRow_tk")]
		public EntitySet<DtsRdeOrdersRxcStdArchive> DtsRdeOrdersRxcStdArchives
		{
			get
			{
				return this._DtsRdeOrdersRxcStdArchives;
			}
			set
			{
				this._DtsRdeOrdersRxcStdArchives.Assign(value);
			}
		}
		
		[Association(Name="DtsRdeStdArchive_DtsRdeOrdersStdArchive", Storage="_DtsRdeStdArchive", ThisKey="headerRow_tk", OtherKey="headerRow_tk", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DtsRdeStdArchive DtsRdeStdArchive
		{
			get
			{
				return this._DtsRdeStdArchive.Entity;
			}
			set
			{
				DtsRdeStdArchive previousValue = this._DtsRdeStdArchive.Entity;
				if (((previousValue != value) 
							|| (this._DtsRdeStdArchive.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DtsRdeStdArchive.Entity = null;
						previousValue.DtsRdeOrdersStdArchives.Remove(this);
					}
					this._DtsRdeStdArchive.Entity = value;
					if ((value != null))
					{
						value.DtsRdeOrdersStdArchives.Add(this);
						this._headerRow_tk = value.headerRow_tk;
					}
					else
					{
						this._headerRow_tk = default(decimal);
					}
					this.SendPropertyChanged("DtsRdeStdArchive");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DtsRdeOrdersRxcStdArchives(DtsRdeOrdersRxcStdArchive entity)
		{
			this.SendPropertyChanging();
			entity.DtsRdeOrdersStdArchive = this;
		}
		
		private void detach_DtsRdeOrdersRxcStdArchives(DtsRdeOrdersRxcStdArchive entity)
		{
			this.SendPropertyChanging();
			entity.DtsRdeOrdersStdArchive = null;
		}
	}
	
	[Table(Name="dbo.DtsRdeOrdersRxcStdArchive")]
	public partial class DtsRdeOrdersRxcStdArchive : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _headerRow_tk;
		
		private int _orderRow_tk;
		
		private int _orderRxcRow_tk;
		
		private string _RDE_Orders_RXC;
		
		private string _RDE_Orders_RXC_RxComponentType;
		
		private string _RDE_Orders_RXC_ComponentCodeIdentifier;
		
		private string _RDE_Orders_RXC_ComponentCodeText;
		
		private string _RDE_Orders_RXC_ComponentCodeAlternateText;
		
		private string _RDE_Orders_RXC_ComponentCodeNameOfCodingSystem;
		
		private string _RDE_Orders_RXC_ComponentAmount;
		
		private string _RDE_Orders_RXC_ComponentUnitsIdentifier;
		
		private string _RDE_Orders_RXC_ComponentUnitsText;
		
		private string _RDE_Orders_RXC_ComponentUnitsAlternateText;
		
		private string _RDE_Orders_RXC_ComponentUnitsNameOfCodingSystem;
		
		private string _RDE_Orders_RXC_ComponentStrength;
		
		private string _RDE_Orders_RXC_ComponentStrengthUnitsIdentifier;
		
		private string _RDE_Orders_RXC_ComponentStrengthUnitsText;
		
		private string _RDE_Orders_RXC_ComponentStrengthUnitsAlternateText;
		
		private string _RDE_Orders_RXC_ComponentStrengthUnitsNameOfCodingSystem;
		
		private string _RDE_Orders_RXC_SupplementaryCode;
		
		private EntityRef<DtsRdeOrdersStdArchive> _DtsRdeOrdersStdArchive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnheaderRow_tkChanging(decimal value);
    partial void OnheaderRow_tkChanged();
    partial void OnorderRow_tkChanging(int value);
    partial void OnorderRow_tkChanged();
    partial void OnorderRxcRow_tkChanging(int value);
    partial void OnorderRxcRow_tkChanged();
    partial void OnRDE_Orders_RXCChanging(string value);
    partial void OnRDE_Orders_RXCChanged();
    partial void OnRDE_Orders_RXC_RxComponentTypeChanging(string value);
    partial void OnRDE_Orders_RXC_RxComponentTypeChanged();
    partial void OnRDE_Orders_RXC_ComponentCodeIdentifierChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentCodeIdentifierChanged();
    partial void OnRDE_Orders_RXC_ComponentCodeTextChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentCodeTextChanged();
    partial void OnRDE_Orders_RXC_ComponentCodeAlternateTextChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentCodeAlternateTextChanged();
    partial void OnRDE_Orders_RXC_ComponentCodeNameOfCodingSystemChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentCodeNameOfCodingSystemChanged();
    partial void OnRDE_Orders_RXC_ComponentAmountChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentAmountChanged();
    partial void OnRDE_Orders_RXC_ComponentUnitsIdentifierChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentUnitsIdentifierChanged();
    partial void OnRDE_Orders_RXC_ComponentUnitsTextChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentUnitsTextChanged();
    partial void OnRDE_Orders_RXC_ComponentUnitsAlternateTextChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentUnitsAlternateTextChanged();
    partial void OnRDE_Orders_RXC_ComponentUnitsNameOfCodingSystemChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentUnitsNameOfCodingSystemChanged();
    partial void OnRDE_Orders_RXC_ComponentStrengthChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentStrengthChanged();
    partial void OnRDE_Orders_RXC_ComponentStrengthUnitsIdentifierChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentStrengthUnitsIdentifierChanged();
    partial void OnRDE_Orders_RXC_ComponentStrengthUnitsTextChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentStrengthUnitsTextChanged();
    partial void OnRDE_Orders_RXC_ComponentStrengthUnitsAlternateTextChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentStrengthUnitsAlternateTextChanged();
    partial void OnRDE_Orders_RXC_ComponentStrengthUnitsNameOfCodingSystemChanging(string value);
    partial void OnRDE_Orders_RXC_ComponentStrengthUnitsNameOfCodingSystemChanged();
    partial void OnRDE_Orders_RXC_SupplementaryCodeChanging(string value);
    partial void OnRDE_Orders_RXC_SupplementaryCodeChanged();
    #endregion
		
		public DtsRdeOrdersRxcStdArchive()
		{
			this._DtsRdeOrdersStdArchive = default(EntityRef<DtsRdeOrdersStdArchive>);
			OnCreated();
		}
		
		[Column(Storage="_headerRow_tk", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal headerRow_tk
		{
			get
			{
				return this._headerRow_tk;
			}
			set
			{
				if ((this._headerRow_tk != value))
				{
					if (this._DtsRdeOrdersStdArchive.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnheaderRow_tkChanging(value);
					this.SendPropertyChanging();
					this._headerRow_tk = value;
					this.SendPropertyChanged("headerRow_tk");
					this.OnheaderRow_tkChanged();
				}
			}
		}
		
		[Column(Storage="_orderRow_tk", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int orderRow_tk
		{
			get
			{
				return this._orderRow_tk;
			}
			set
			{
				if ((this._orderRow_tk != value))
				{
					if (this._DtsRdeOrdersStdArchive.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnorderRow_tkChanging(value);
					this.SendPropertyChanging();
					this._orderRow_tk = value;
					this.SendPropertyChanged("orderRow_tk");
					this.OnorderRow_tkChanged();
				}
			}
		}
		
		[Column(Storage="_orderRxcRow_tk", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int orderRxcRow_tk
		{
			get
			{
				return this._orderRxcRow_tk;
			}
			set
			{
				if ((this._orderRxcRow_tk != value))
				{
					this.OnorderRxcRow_tkChanging(value);
					this.SendPropertyChanging();
					this._orderRxcRow_tk = value;
					this.SendPropertyChanged("orderRxcRow_tk");
					this.OnorderRxcRow_tkChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC", DbType="VarChar(50)")]
		public string RDE_Orders_RXC
		{
			get
			{
				return this._RDE_Orders_RXC;
			}
			set
			{
				if ((this._RDE_Orders_RXC != value))
				{
					this.OnRDE_Orders_RXCChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC = value;
					this.SendPropertyChanged("RDE_Orders_RXC");
					this.OnRDE_Orders_RXCChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_RxComponentType", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_RxComponentType
		{
			get
			{
				return this._RDE_Orders_RXC_RxComponentType;
			}
			set
			{
				if ((this._RDE_Orders_RXC_RxComponentType != value))
				{
					this.OnRDE_Orders_RXC_RxComponentTypeChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_RxComponentType = value;
					this.SendPropertyChanged("RDE_Orders_RXC_RxComponentType");
					this.OnRDE_Orders_RXC_RxComponentTypeChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentCodeIdentifier", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentCodeIdentifier
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentCodeIdentifier;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentCodeIdentifier != value))
				{
					this.OnRDE_Orders_RXC_ComponentCodeIdentifierChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentCodeIdentifier = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentCodeIdentifier");
					this.OnRDE_Orders_RXC_ComponentCodeIdentifierChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentCodeText", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentCodeText
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentCodeText;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentCodeText != value))
				{
					this.OnRDE_Orders_RXC_ComponentCodeTextChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentCodeText = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentCodeText");
					this.OnRDE_Orders_RXC_ComponentCodeTextChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentCodeAlternateText", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentCodeAlternateText
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentCodeAlternateText;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentCodeAlternateText != value))
				{
					this.OnRDE_Orders_RXC_ComponentCodeAlternateTextChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentCodeAlternateText = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentCodeAlternateText");
					this.OnRDE_Orders_RXC_ComponentCodeAlternateTextChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentCodeNameOfCodingSystem", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentCodeNameOfCodingSystem
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentCodeNameOfCodingSystem;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentCodeNameOfCodingSystem != value))
				{
					this.OnRDE_Orders_RXC_ComponentCodeNameOfCodingSystemChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentCodeNameOfCodingSystem = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentCodeNameOfCodingSystem");
					this.OnRDE_Orders_RXC_ComponentCodeNameOfCodingSystemChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentAmount", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentAmount
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentAmount;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentAmount != value))
				{
					this.OnRDE_Orders_RXC_ComponentAmountChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentAmount = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentAmount");
					this.OnRDE_Orders_RXC_ComponentAmountChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentUnitsIdentifier", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentUnitsIdentifier
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentUnitsIdentifier;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentUnitsIdentifier != value))
				{
					this.OnRDE_Orders_RXC_ComponentUnitsIdentifierChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentUnitsIdentifier = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentUnitsIdentifier");
					this.OnRDE_Orders_RXC_ComponentUnitsIdentifierChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentUnitsText", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentUnitsText
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentUnitsText;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentUnitsText != value))
				{
					this.OnRDE_Orders_RXC_ComponentUnitsTextChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentUnitsText = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentUnitsText");
					this.OnRDE_Orders_RXC_ComponentUnitsTextChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentUnitsAlternateText", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentUnitsAlternateText
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentUnitsAlternateText;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentUnitsAlternateText != value))
				{
					this.OnRDE_Orders_RXC_ComponentUnitsAlternateTextChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentUnitsAlternateText = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentUnitsAlternateText");
					this.OnRDE_Orders_RXC_ComponentUnitsAlternateTextChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentUnitsNameOfCodingSystem", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentUnitsNameOfCodingSystem
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentUnitsNameOfCodingSystem;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentUnitsNameOfCodingSystem != value))
				{
					this.OnRDE_Orders_RXC_ComponentUnitsNameOfCodingSystemChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentUnitsNameOfCodingSystem = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentUnitsNameOfCodingSystem");
					this.OnRDE_Orders_RXC_ComponentUnitsNameOfCodingSystemChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentStrength", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentStrength
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentStrength;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentStrength != value))
				{
					this.OnRDE_Orders_RXC_ComponentStrengthChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentStrength = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentStrength");
					this.OnRDE_Orders_RXC_ComponentStrengthChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentStrengthUnitsIdentifier", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentStrengthUnitsIdentifier
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentStrengthUnitsIdentifier;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentStrengthUnitsIdentifier != value))
				{
					this.OnRDE_Orders_RXC_ComponentStrengthUnitsIdentifierChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentStrengthUnitsIdentifier = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentStrengthUnitsIdentifier");
					this.OnRDE_Orders_RXC_ComponentStrengthUnitsIdentifierChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentStrengthUnitsText", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentStrengthUnitsText
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentStrengthUnitsText;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentStrengthUnitsText != value))
				{
					this.OnRDE_Orders_RXC_ComponentStrengthUnitsTextChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentStrengthUnitsText = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentStrengthUnitsText");
					this.OnRDE_Orders_RXC_ComponentStrengthUnitsTextChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentStrengthUnitsAlternateText", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentStrengthUnitsAlternateText
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentStrengthUnitsAlternateText;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentStrengthUnitsAlternateText != value))
				{
					this.OnRDE_Orders_RXC_ComponentStrengthUnitsAlternateTextChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentStrengthUnitsAlternateText = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentStrengthUnitsAlternateText");
					this.OnRDE_Orders_RXC_ComponentStrengthUnitsAlternateTextChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_ComponentStrengthUnitsNameOfCodingSystem", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_ComponentStrengthUnitsNameOfCodingSystem
		{
			get
			{
				return this._RDE_Orders_RXC_ComponentStrengthUnitsNameOfCodingSystem;
			}
			set
			{
				if ((this._RDE_Orders_RXC_ComponentStrengthUnitsNameOfCodingSystem != value))
				{
					this.OnRDE_Orders_RXC_ComponentStrengthUnitsNameOfCodingSystemChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_ComponentStrengthUnitsNameOfCodingSystem = value;
					this.SendPropertyChanged("RDE_Orders_RXC_ComponentStrengthUnitsNameOfCodingSystem");
					this.OnRDE_Orders_RXC_ComponentStrengthUnitsNameOfCodingSystemChanged();
				}
			}
		}
		
		[Column(Storage="_RDE_Orders_RXC_SupplementaryCode", DbType="VarChar(50)")]
		public string RDE_Orders_RXC_SupplementaryCode
		{
			get
			{
				return this._RDE_Orders_RXC_SupplementaryCode;
			}
			set
			{
				if ((this._RDE_Orders_RXC_SupplementaryCode != value))
				{
					this.OnRDE_Orders_RXC_SupplementaryCodeChanging(value);
					this.SendPropertyChanging();
					this._RDE_Orders_RXC_SupplementaryCode = value;
					this.SendPropertyChanged("RDE_Orders_RXC_SupplementaryCode");
					this.OnRDE_Orders_RXC_SupplementaryCodeChanged();
				}
			}
		}
		
		[Association(Name="DtsRdeOrdersStdArchive_DtsRdeOrdersRxcStdArchive", Storage="_DtsRdeOrdersStdArchive", ThisKey="headerRow_tk,orderRow_tk", OtherKey="headerRow_tk,orderRow_tk", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DtsRdeOrdersStdArchive DtsRdeOrdersStdArchive
		{
			get
			{
				return this._DtsRdeOrdersStdArchive.Entity;
			}
			set
			{
				DtsRdeOrdersStdArchive previousValue = this._DtsRdeOrdersStdArchive.Entity;
				if (((previousValue != value) 
							|| (this._DtsRdeOrdersStdArchive.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DtsRdeOrdersStdArchive.Entity = null;
						previousValue.DtsRdeOrdersRxcStdArchives.Remove(this);
					}
					this._DtsRdeOrdersStdArchive.Entity = value;
					if ((value != null))
					{
						value.DtsRdeOrdersRxcStdArchives.Add(this);
						this._headerRow_tk = value.headerRow_tk;
						this._orderRow_tk = value.orderRow_tk;
					}
					else
					{
						this._headerRow_tk = default(decimal);
						this._orderRow_tk = default(int);
					}
					this.SendPropertyChanged("DtsRdeOrdersStdArchive");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
