<?xml version="1.0" encoding="utf-8"?>
<Database Name="Mapping" Class="MapClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=cdprod100;Initial Catalog=Mapping;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MappingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CSS_MasterSiteDrugName" Member="CSS_MasterSiteDrugNames">
    <Type Name="CSS_MasterSiteDrugName">
      <Column Name="MasterSiteDrugNameId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MasterSiteDrugName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MasterMappedPharmacyDrug" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="InsertedLDT" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CSS_MasterSiteDrugUnit" Member="CSS_MasterSiteDrugUnits">
    <Type Name="CSS_MasterSiteDrugUnit">
      <Column Name="MasterSiteDrugUnitId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MasterSiteDrugUnit" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MasterMappedPharmacyUnit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InsertedLDT" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CSS_MasterSiteRoute" Member="CSS_MasterSiteRoutes">
    <Type Name="CSS_MasterSiteRoute">
      <Column Name="MasterSiteRouteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MasterSiteRouteCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MasterMappedPharmacyRoute" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InsertedLDT" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CSS_MasterRepeatPattern" Member="CSS_MasterRepeatPatterns">
    <Type Name="CSS_MasterRepeatPattern">
      <Column Name="MasterRepeatPatternId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MasterRepeatPatternCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MasterMappedRepeatPattern" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InsertedLDT" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>