<?xml version="1.0" encoding="utf-8"?>
<Database Name="ClientDictionary" Class="SiteClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=CDPROD100;Initial Catalog=ClientDictionary;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ClientDictionaryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Connections" Member="Connections">
    <Type Name="Connection">
      <Column Name="connection_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="connection_string" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="ConnVendor_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Connection_SiteConnection" Member="SiteConnections" ThisKey="connection_id" OtherKey="Connection_id" Type="SiteConnection" />
    </Type>
  </Table>
  <Table Name="dbo.SiteConnections" Member="SiteConnections">
    <Type Name="SiteConnection">
      <Column Name="SiteCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Connection_DBVersion" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Connection_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ConnType_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Connection_SiteConnection" Member="Connection" ThisKey="Connection_id" OtherKey="connection_id" Type="Connection" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetSiteSummaryDistinct" Method="GetSiteSummaryDistinct">
    <ElementType Name="GetSiteSummaryDistinctResult">
      <Column Name="SiteCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>